spring:
  profiles:
    active: dev
  # 스프링 3.0 이후 context 경로를 위한 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    user:
      name: sinny@gmail.com
      password: 1111
# context 경로(배포경로와 겹칠 때 주석처리하면 됨 근데 굳이 겹치게 할 필요는 없음)
server:
  servlet:
    context-path:
# 내맘대로 설정
rland:
  jwt:
    secret: "EW9eWHfv5jkEZ3IqtUW8SCuuNcxFmT7gbqcKQ9+e2eTkyxsJoS7E2/qjQyGEtcjqmGFbHPll9E/KTnOB8i1cTg=="
